apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: ingress-nginx-values
    namespace: ingress-nginx
    files:
      - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true
