apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gophergate

resources:
  - namespace.yaml
  - secret-db-credentials.sops.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: gophergate-values
    files:
      - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true
